services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data


  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  payment-process:
    build: ./payment-process
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - kafka
      - health-check
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment-process
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    deploy:
      resources:
        limits:
          cpus: "3.0"

  payment-pagpay:
    build: ./payment-pagpay
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment-pagpay
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    deploy:
      resources:
        limits:
          cpus: "2.0"

  payment-pagsafe:
    build: ./payment-pagsafe
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment-pagsafe
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    deploy:
      resources:
        limits:
          cpus: "2.0"

  health-check:
    build: ./health-check
    ports:
      - "8003:8003"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/health-check
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  pgdata: